### ISSUE TITLE
.INCLUDE directive inside a statement block?

### ISSUE THREAD

**Issue by tmm1** [TekWizely/bash-tpl#19] opened 2023-07-26 03:40 UTC
hi, thanks for a great project

i'm trying to use .INCLUDE inside a statement block but can't quite figure it out. is it supported?

**Comment by tmm1** [comment] 2023-07-26 03:45
I think the answer is no, as explained [here](https://github.com/TekWizely/bash-tpl/issues/18#issuecomment-1585054229):

> the .INCLUDE directive is a 'compile-time' feature, but the % directive is a runtime feature

**Comment by TekWizely** [comment] 2023-07-29 18:37
Hi @tmm1 you figured it out yes the issue is compiletime vs runtime.

You might also have a read [here](https://github.com/TekWizely/bash-tpl/issues/16#issuecomment-1535171199) where the user uses bash-tpl as a static site generator tool.

I came up with a strategy (and a makefile) to host a directory of bash-tpl templates that all compile to a directory of .sh/source scripts and you include them using the `source` at runtime.

See if anything there might be useful and lemme know your thoughts!

Thanks for taking the time to report an issue and for your interest in my project!

-TW

**Comment by TekWizely** [comment] 2023-08-14 02:17
Hey @tmm1 just checking in to see if you got my reply - lemme know if you wanna continue the discussion !

**Comment by TekWizely** [comment] 2024-05-31 18:33
Hi @tmm1  I'm going to close this issue, but wanted to add one last comment.

I moved the Makefile example mentioned earlier into the Discussion area:
* https://github.com/TekWizely/bash-tpl/discussions/22

You can use a `source path/to/file` in your statement block to include a file at runtime.  In the case for a template you would be sourcing the compiled template.

I am working on an idea to add a .SOURCE directive for sourcing other compiled templates that could easily send the current line indent information along so that output generated from the sourced template would be consistent.

Thanks again for your interest in my project and taking the time to report an issue.

-TW

**Closed by TekWizely** 2024-05-31 18:33 UTC
